# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  # rootDir: 'my-app'
  buildDir: 'build'

steps:
  
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      # echo "`pwd`"
      # [[ -d $(rootDir) ]] || mkdir $(rootDir)
      # echo "b1 `ls -l`"
      # cd $(rootDir)
      # echo "b2 `ls -l`"
      npm install
      npm run build
      echo "b3 `ls -l`"
      # cd ..
      # echo "b4 `ls -l`"
    displayName: 'npm install and build'   
 
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(buildDir)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

      